name: CI
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: olafurpg/setup-scala@v10
      with:
        java-version: "adopt@1.8"
    - run: sbt pushRemoteCache
    - run: cat target/scala-2.13/routes/main/router/RoutesPrefix.scala
    - run: sbt clean pullRemoteCache compile
    - run: cat target/scala-2.13/routes/main/router/RoutesPrefix.scala
